format: fix callAndRead for python3
Fixes the following error:

    Traceback (most recent call last):
      File "/opt/slapos/eggs/slapos.core-1.7.9-py3.7.egg/slapos/cli/entry.py", line 305, in run_subcommand
        result = cmd.run(parsed_args)
      File "/opt/slapos/eggs/slapos.core-1.7.9-py3.7.egg/slapos/cli/command.py", line 56, in run
        return self.take_action(parsed_args)
      File "/opt/slapos/eggs/slapos.core-1.7.9-py3.7.egg/slapos/cli/format.py", line 128, in take_action
        do_format(conf=conf)
      File "/opt/slapos/eggs/slapos.core-1.7.9-py3.7.egg/slapos/format.py", line 1396, in do_format
        create_tap=conf.create_tap)
      File "/opt/slapos/eggs/slapos.core-1.7.9-py3.7.egg/slapos/format.py", line 655, in format
        partition.address_list.append(self.interface.addIPv6Address())
      File "/opt/slapos/eggs/slapos.core-1.7.9-py3.7.egg/slapos/format.py", line 1223, in addIPv6Address
        if self._addSystemAddress(addr, netmask, tap=tap):
      File "/opt/slapos/eggs/slapos.core-1.7.9-py3.7.egg/slapos/format.py", line 1086, in _addSystemAddress
        for l in result.split('\n'):
    TypeError: a bytes-like object is required, not 'str'