slapgrid: fix _updateCertificate in python3
Traceback (most recent call last):
  File "/opt/slapos/eggs/slapos.core-1.7.10-py3.7.egg/slapos/grid/slapgrid.py", line 1435, in processComputerPartitionList
    self.processComputerPartition(computer_partition)
  File "/opt/slapos/eggs/slapos.core-1.7.10-py3.7.egg/slapos/grid/slapgrid.py", line 1329, in processComputerPartition
    raise e
  File "/opt/slapos/eggs/slapos.core-1.7.10-py3.7.egg/slapos/grid/slapgrid.py", line 1254, in processComputerPartition
    local_partition._updateCertificate()
  File "/opt/slapos/eggs/slapos.core-1.7.10-py3.7.egg/slapos/grid/SlapObject.py", line 513, in _updateCertificate
    fout.write(new_content)
TypeError: a bytes-like object is required, not 'str'

Also add test for the failure.