util.rmtree: fix for python3
On python3, deleting a chmoded folder causes this error:

    Traceback (most recent call last):
      File "/usr/lib/python3.7/shutil.py", line 423, in _rmtree_safe_fd
        dirfd = os.open(entry.name, os.O_RDONLY, dir_fd=topfd)
    PermissionError: [Errno 13] Permission denied: 'directory'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "slapos.core/slapos/grid/slapgrid.py", line 607, in processSoftwareReleaseList
        software.destroy()
      File "slapos.core/slapos/grid/SlapObject.py", line 360, in destroy
        rmtree(self.software_path)
      File "slapos.core/slapos/util.py", line 267, in rmtree
        shutil.rmtree(path, onerror=chmod_retry)
      File "/usr/lib/python3.7/shutil.py", line 491, in rmtree
        _rmtree_safe_fd(fd, path, onerror)
      File "/usr/lib/python3.7/shutil.py", line 425, in _rmtree_safe_fd
        onerror(os.open, fullname, sys.exc_info())
      File "slapos.core/slapos/util.py", line 264, in chmod_retry
        func(failed_path)
    TypeError: open() missing required argument 'flags' (pos 2)

We cannot call the failed `func` without arguments here, but we need to handle
the failure listing the directory using the fd variant of the function by
retrying the whole deletion after changing mode.